# Generated by Django 3.2.12 on 2024-03-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task2',
        ),
    ]
